"""add admin flag

Revision ID: 2184c2299da5
Revises: 4ce6b191521f
Create Date: 2026-09-21 02:51:06.157296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2184c2299da5'
down_revision: Union[str, Sequence[str], None] = '4ce6b191521f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "business_applications",
        "password_hash",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )

    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.create_index(
        op.f("ix_users_is_admin"),
        "users",
        ["is_admin"],
        unique=False,
    )

    op.alter_column(
        "users",
        "is_admin",
        server_default=None,
    )

    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_users_is_admin"),
        table_name="users",
    )

    op.drop_column(
        "users",
        "is_admin",
    )

    op.alter_column(
        "business_applications",
        "password_hash",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )

    # ### end Alembic commands ###