"""add business applications

Revision ID: 4ce6b191521f
Revises: 5ee4ab982293
Create Date: 2026-09-21 02:40:47.719761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce6b191521f'
down_revision: Union[str, Sequence[str], None] = '5ee4ab982293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('business_phone', sa.String(length=30), nullable=True),
    sa.Column('business_email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='business_application_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_applications_email'), 'business_applications', ['email'], unique=False)
    op.create_index(op.f('ix_business_applications_status'), 'business_applications', ['status'], unique=False)
    op.create_index('ix_business_applications_status_created_at', 'business_applications', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_applications_status_created_at', table_name='business_applications')
    op.drop_index(op.f('ix_business_applications_status'), table_name='business_applications')
    op.drop_index(op.f('ix_business_applications_email'), table_name='business_applications')
    op.drop_table('business_applications')
    # ### end Alembic commands ###
